/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as StudiesRouteImport } from './routes/studies'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ViewerStudyIdRouteImport } from './routes/viewer.$studyId'
import { Route as ApiImagingUploadRouteImport } from './routes/api/imaging/upload'
import { Route as ApiImagingMprRouteImport } from './routes/api/imaging/mpr'
import { Route as ApiImagingMeasurementsRouteImport } from './routes/api/imaging/measurements'
import { Route as ApiImagingDemosRouteImport } from './routes/api/imaging/demos'
import { Route as ApiImagingCenterlineRouteImport } from './routes/api/imaging/centerline'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiImagingSeriesSeriesIdRouteImport } from './routes/api/imaging/series.$seriesId'
import { Route as ApiImagingSegmentationIdRouteImport } from './routes/api/imaging/segmentation.$id'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const StudiesRoute = StudiesRouteImport.update({
  id: '/studies',
  path: '/studies',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewerStudyIdRoute = ViewerStudyIdRouteImport.update({
  id: '/viewer/$studyId',
  path: '/viewer/$studyId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImagingUploadRoute = ApiImagingUploadRouteImport.update({
  id: '/api/imaging/upload',
  path: '/api/imaging/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImagingMprRoute = ApiImagingMprRouteImport.update({
  id: '/api/imaging/mpr',
  path: '/api/imaging/mpr',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImagingMeasurementsRoute = ApiImagingMeasurementsRouteImport.update({
  id: '/api/imaging/measurements',
  path: '/api/imaging/measurements',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImagingDemosRoute = ApiImagingDemosRouteImport.update({
  id: '/api/imaging/demos',
  path: '/api/imaging/demos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImagingCenterlineRoute = ApiImagingCenterlineRouteImport.update({
  id: '/api/imaging/centerline',
  path: '/api/imaging/centerline',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImagingSeriesSeriesIdRoute =
  ApiImagingSeriesSeriesIdRouteImport.update({
    id: '/api/imaging/series/$seriesId',
    path: '/api/imaging/series/$seriesId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiImagingSegmentationIdRoute =
  ApiImagingSegmentationIdRouteImport.update({
    id: '/api/imaging/segmentation/$id',
    path: '/api/imaging/segmentation/$id',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/studies': typeof StudiesRoute
  '/upload': typeof UploadRoute
  '/viewer/$studyId': typeof ViewerStudyIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/imaging/centerline': typeof ApiImagingCenterlineRoute
  '/api/imaging/demos': typeof ApiImagingDemosRoute
  '/api/imaging/measurements': typeof ApiImagingMeasurementsRoute
  '/api/imaging/mpr': typeof ApiImagingMprRoute
  '/api/imaging/upload': typeof ApiImagingUploadRoute
  '/api/imaging/segmentation/$id': typeof ApiImagingSegmentationIdRoute
  '/api/imaging/series/$seriesId': typeof ApiImagingSeriesSeriesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/studies': typeof StudiesRoute
  '/upload': typeof UploadRoute
  '/viewer/$studyId': typeof ViewerStudyIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/imaging/centerline': typeof ApiImagingCenterlineRoute
  '/api/imaging/demos': typeof ApiImagingDemosRoute
  '/api/imaging/measurements': typeof ApiImagingMeasurementsRoute
  '/api/imaging/mpr': typeof ApiImagingMprRoute
  '/api/imaging/upload': typeof ApiImagingUploadRoute
  '/api/imaging/segmentation/$id': typeof ApiImagingSegmentationIdRoute
  '/api/imaging/series/$seriesId': typeof ApiImagingSeriesSeriesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/studies': typeof StudiesRoute
  '/upload': typeof UploadRoute
  '/viewer/$studyId': typeof ViewerStudyIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/imaging/centerline': typeof ApiImagingCenterlineRoute
  '/api/imaging/demos': typeof ApiImagingDemosRoute
  '/api/imaging/measurements': typeof ApiImagingMeasurementsRoute
  '/api/imaging/mpr': typeof ApiImagingMprRoute
  '/api/imaging/upload': typeof ApiImagingUploadRoute
  '/api/imaging/segmentation/$id': typeof ApiImagingSegmentationIdRoute
  '/api/imaging/series/$seriesId': typeof ApiImagingSeriesSeriesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/studies'
    | '/upload'
    | '/viewer/$studyId'
    | '/api/auth/$'
    | '/api/imaging/centerline'
    | '/api/imaging/demos'
    | '/api/imaging/measurements'
    | '/api/imaging/mpr'
    | '/api/imaging/upload'
    | '/api/imaging/segmentation/$id'
    | '/api/imaging/series/$seriesId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/studies'
    | '/upload'
    | '/viewer/$studyId'
    | '/api/auth/$'
    | '/api/imaging/centerline'
    | '/api/imaging/demos'
    | '/api/imaging/measurements'
    | '/api/imaging/mpr'
    | '/api/imaging/upload'
    | '/api/imaging/segmentation/$id'
    | '/api/imaging/series/$seriesId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/studies'
    | '/upload'
    | '/viewer/$studyId'
    | '/api/auth/$'
    | '/api/imaging/centerline'
    | '/api/imaging/demos'
    | '/api/imaging/measurements'
    | '/api/imaging/mpr'
    | '/api/imaging/upload'
    | '/api/imaging/segmentation/$id'
    | '/api/imaging/series/$seriesId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  StudiesRoute: typeof StudiesRoute
  UploadRoute: typeof UploadRoute
  ViewerStudyIdRoute: typeof ViewerStudyIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiImagingCenterlineRoute: typeof ApiImagingCenterlineRoute
  ApiImagingDemosRoute: typeof ApiImagingDemosRoute
  ApiImagingMeasurementsRoute: typeof ApiImagingMeasurementsRoute
  ApiImagingMprRoute: typeof ApiImagingMprRoute
  ApiImagingUploadRoute: typeof ApiImagingUploadRoute
  ApiImagingSegmentationIdRoute: typeof ApiImagingSegmentationIdRoute
  ApiImagingSeriesSeriesIdRoute: typeof ApiImagingSeriesSeriesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studies': {
      id: '/studies'
      path: '/studies'
      fullPath: '/studies'
      preLoaderRoute: typeof StudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viewer/$studyId': {
      id: '/viewer/$studyId'
      path: '/viewer/$studyId'
      fullPath: '/viewer/$studyId'
      preLoaderRoute: typeof ViewerStudyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/imaging/upload': {
      id: '/api/imaging/upload'
      path: '/api/imaging/upload'
      fullPath: '/api/imaging/upload'
      preLoaderRoute: typeof ApiImagingUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/imaging/mpr': {
      id: '/api/imaging/mpr'
      path: '/api/imaging/mpr'
      fullPath: '/api/imaging/mpr'
      preLoaderRoute: typeof ApiImagingMprRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/imaging/measurements': {
      id: '/api/imaging/measurements'
      path: '/api/imaging/measurements'
      fullPath: '/api/imaging/measurements'
      preLoaderRoute: typeof ApiImagingMeasurementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/imaging/demos': {
      id: '/api/imaging/demos'
      path: '/api/imaging/demos'
      fullPath: '/api/imaging/demos'
      preLoaderRoute: typeof ApiImagingDemosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/imaging/centerline': {
      id: '/api/imaging/centerline'
      path: '/api/imaging/centerline'
      fullPath: '/api/imaging/centerline'
      preLoaderRoute: typeof ApiImagingCenterlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/imaging/series/$seriesId': {
      id: '/api/imaging/series/$seriesId'
      path: '/api/imaging/series/$seriesId'
      fullPath: '/api/imaging/series/$seriesId'
      preLoaderRoute: typeof ApiImagingSeriesSeriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/imaging/segmentation/$id': {
      id: '/api/imaging/segmentation/$id'
      path: '/api/imaging/segmentation/$id'
      fullPath: '/api/imaging/segmentation/$id'
      preLoaderRoute: typeof ApiImagingSegmentationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  StudiesRoute: StudiesRoute,
  UploadRoute: UploadRoute,
  ViewerStudyIdRoute: ViewerStudyIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiImagingCenterlineRoute: ApiImagingCenterlineRoute,
  ApiImagingDemosRoute: ApiImagingDemosRoute,
  ApiImagingMeasurementsRoute: ApiImagingMeasurementsRoute,
  ApiImagingMprRoute: ApiImagingMprRoute,
  ApiImagingUploadRoute: ApiImagingUploadRoute,
  ApiImagingSegmentationIdRoute: ApiImagingSegmentationIdRoute,
  ApiImagingSeriesSeriesIdRoute: ApiImagingSeriesSeriesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
